"""remove unused fields and tables

Revision ID: 5744ff2223eb
Revises: 03a857cdef7a
Create Date: 2026-06-13 19:08:59.024811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5744ff2223eb'
down_revision: Union[str, Sequence[str], None] = '03a857cdef7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notification_ibfk_1', 'notification', type_='foreignkey')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.add_column('user', sa.Column('banned_token', sa.String(length=500), nullable=True))
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('ADMIN', 'USER', 'GUEST'),
               type_=sa.Enum('ADMIN', 'USER', 'GUEST', name='role_enum', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('verification_token'), table_name='user')
    op.drop_column('user', 'verified')
    op.drop_column('user', 'verification_token')
    op.drop_column('user', 'token_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_expires_at', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('verification_token', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('user', sa.Column('verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index(op.f('verification_token'), 'user', ['verification_token'], unique=True)
    op.alter_column('user', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', 'GUEST', name='role_enum', native_enum=False),
               type_=mysql.ENUM('ADMIN', 'USER', 'GUEST'),
               existing_nullable=False)
    op.drop_column('user', 'banned_token')
    op.create_table('notification',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('notification_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    # ### end Alembic commands ###
